/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "sat_ops.check" instead.
 */

#include <check.h>

#line 1 "sat_ops.check"
#include "sat_ops.h"

START_TEST(sat_ops)
{
#line 4
    fail_unless(sat_unsigned_add(3, 2) == 5, "sat unsigned borked");


}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, sat_ops);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
